### PR TITLE
Update withings api breaking changes

### PR DESCRIPTION
**Pull request by fakarava94**
Update token access accordin to new policy : https://support.withings.com/hc/en-us/articles/360016745358--BREAKING-Deprecating-access-and-refresh-tokens-endpoints

Create a new Withings Endpoint

Update Garmin username (displayName) search

### CODE REVIEW

**Comment by ysaliens** [comment]
This fixes the Withings API error but I'm still having issues with Garmin -

I get 403s back when trying to authenticate. Credentials are correct.

**Comment by ysaliens** [comment]
Still not working :/

**Comment by fakarava94** [comment]
Hi,

I pushed a new commit to be tested.

François

**Comment by eitanbehar** [comment]
@fakarava94 Just wanted to let you know that I did a successful sync from withings to garmin using your branch `fix/api-update`
Thanks!!!

**Pull request merged**
